// Copyright (c) 2026 Huawei Device Co., Ltd.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef FFI_HITRACE_BRIDGE_H
#define FFI_HITRACE_BRIDGE_H

#include "cxx.h"

namespace OHOS::HiviewDFX {

// FfiHiTraceId is a CXX shared struct defined in wrapper.rs.h (generated by CXX).
// Named FfiHiTraceId to avoid collision with the system HiTraceId class.
struct FfiHiTraceId;

FfiHiTraceId begin_section(rust::Str name);
void end_section();
FfiHiTraceId create_trace_id(rust::Str name);
FfiHiTraceId get_current_trace_id();
bool is_trace_enabled();

} // namespace OHOS::HiviewDFX

#endif // FFI_HITRACE_BRIDGE_H
